version: '3.8'

services:
  db:
    image: postgres
    container_name: my-postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg-network

  frontend:
    image: nginx:alpine
    container_name: my_frontend
    volumes:
      - ${PWD}/frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/frontend/public:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    networks:
      - pg-network

volumes:
  pgdata:

networks:
  pg-network:
    driver: bridge